### ISSUE TITLE
新版本exe 报错

### ISSUE THREAD

**Issue by yygcom** [Davy-Zhou/pdf_add_bookmark_semi#1]
Traceback (most recent call last):
  File "pdf_add_bookmark_semi.py", line 244, in <module>
    main()
  File "pdf_add_bookmark_semi.py", line 237, in main
    pike_add_bookmark()
  File "pdf_add_bookmark_semi.py", line 154, in pike_add_bookmark
    L1_item.children.append(L2_item)
UnboundLocalError: local variable 'L1_item' referenced before assignment
[11836] Failed to execute script 'pdf_add_bookmark_semi' due to unhandled exception!

**Comment by Davy-Zhou** [comment]
麻烦发一下书签文件，那个格式化后的txt，带有(Bookmark)后缀那个。问题应该是你的那个书签层次不连续，一级书签没有，后面直接是二级或多级书签了，这个是书签本身的问题，代码除了提示存在书签层次不连续的地方外，代码不好修，需要自己在格式化书签的时候自己改，把书签改成一级书签即可

**Comment by Davy-Zhou** [comment]
```yaml

	目录	14  #就像这级书签，前面没有一级书签，但它应该是一级书签，直接不改就会报错
第1章 电子数据取证概述	1	+23
	1.1 网络犯罪与网络安全	1	+23
	1.2 电子数据概述	3	+23

```

**Comment by Davy-Zhou** [comment]
> Traceback (most recent call last): File "pdf_add_bookmark_semi.py", line 244, in main() File "pdf_add_bookmark_semi.py", line 237, in main pike_add_bookmark() File "pdf_add_bookmark_semi.py", line 154, in pike_add_bookmark L1_item.children.append(L2_item) UnboundLocalError: local variable 'L1_item' referenced before assignment [11836] Failed to execute script 'pdf_add_bookmark_semi' due to unhandled exception!

```yaml
	目录	14  #就像这级书签，前面没有一级书签，但它应该是一级书签，直接不改就会报错
第1章 电子数据取证概述	1	+23
	1.1 网络犯罪与网络安全	1	+23
	1.2 电子数据概述	3	+23
```
